import Head from "next/head";
import React from "react";
import { v4 } from "uuid";
import useBookmark from "../../hooks/useBookmark";
import { TweetWithUser } from "../../interface";
import Body from "../components/Body";
import NavFeed from "../components/NavFeed";
import TweetComponent from "../components/TweetComponent";
import TweetList from "../components/TweetList";

const BookmarkPage = () => {
  const { bookmarks:data } = useBookmark();
  const bookmarks = data?.map((bookmark)=>bookmark.tweet);
  console.log(bookmarks)
  return (
    <Body>
      <Head>
        <title>Bookmarks / Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavFeed title="Bookmarks" />
      <TweetList tweets={bookmarks as TweetWithUser[]} />
      {/* {bookmarks?.map((bookmark) => (
        <TweetComponent key={v4()} tweet={bookmark.tweet as TweetWithUser} />
      ))} */}
    </Body>
  );
};

export default BookmarkPage;
