import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { v4 } from "uuid";
import { UserWithPayloads } from "../../interface";
import Body from "../components/Body";
import NavFeed from "../components/NavFeed";
import PeopleComponent from "../components/PeopleComponent";
import { trpc } from "../utils/trpc";

const connect_people = () => {
  const { data } = trpc.follow.getFollowersRecommendation.useQuery();
  const { data: session } = useSession();
  return (
    <Body>
      <Head>
        <title>Connect / Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavFeed title="Connect" />
      {data
        ?.filter((user) => user.id !== session?.user?.id)
        .map((user: unknown) => (
          <PeopleComponent key={v4()} user={user as unknown as UserWithPayloads} />
        ))}
    </Body>
  );
};

export default connect_people;
