import { useRouter } from "next/router";
import React, { useEffect } from "react";
import Body from "../components/Body";
import Loader from "../components/Loader";
import SearchHeader from "../components/SearchHeader";
import TweetComponent from "../components/TweetComponent";
import { trpc } from "../utils/trpc";
import { Prisma, Tweet, User } from "@prisma/client";
import PeopleComponent from "../components/PeopleComponent";
import NoResults from "../components/NoResults";
import { v4 } from "uuid";
import TweetList from "../components/TweetList";
import Head from "next/head";
import { TweetWithUser } from "../../interface";
import useScrollPosition from "../../hooks/useScrollPosition";
import { useSession } from "next-auth/react";

const SearchPage = () => {
  const router = useRouter();
  const { q, f } = router.query;
  // const { data: searchResults, isLoading } = trpc.tweet.searchTweets.useQuery({
  //   term,
  //   filtering: router.query.f as string,
  // });
  const { data: searchUsers, isLoading: isUserLoading } =
    trpc.user.searchUsers.useQuery({
      term:q as string,
    });
  const scrollPosition = useScrollPosition();

  const { data, isLoading, isFetching, hasNextPage, fetchNextPage } =
    trpc.tweet.searchTweets.useInfiniteQuery(
      {
        limit: 10,
        term: q as string,
        filtering: f as string,
      },
      {
        getNextPageParam: (lastPage) => lastPage?.nextCursor,
      }
    );

  useEffect(() => {
    if (scrollPosition > 90 && hasNextPage && !isFetching) {
      fetchNextPage();
    }
  }, [scrollPosition, isFetching, hasNextPage, fetchNextPage]);

  const tweets = data?.pages.flatMap((page) => page?.tweets) ?? [];
  const { data: session, status } = useSession();
  console.log(data);
  return (
    <Body>
      <Head>
        <title>{q} - Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchHeader />
      {router.query.f !== "people" ? (
        <>{isLoading ? <Loader /> : null}</>
      ) : (
        <>{isLoading ? <Loader /> : null}</>
      )}

     {router.query.f !== "people" ? ( 
      <>
        {tweets?.length === 0 && !isFetching ? (
          <NoResults />
        ) : (
          <>
            <TweetList key={v4()} tweets={tweets as TweetWithUser[]} />
          </>
        )}
      </>
     ) : (
        <>
          {searchUsers?.length === 0 ? (
            <NoResults />
          ) : (
            <>
              {searchUsers?.map((user) => (
                <PeopleComponent user={user} key={v4()} />
              ))}
            </>
          )}
        </>
      )} 
      {isFetching && hasNextPage ? (
        <div className="pb-16">
          <Loader />
        </div>
      ) : null}
    </Body>
  );
};

export default SearchPage;
